from django.contrib import admin
from .models import Rapport_responsable,Responsable,Absence_employe,Employe,Achats_matiereP,Payement_sold_fournisseur,Fournisseur,Produit_Fournisseur,Magasinier,Achats_client_centre,Achats_client,paye_credit,Client,Transfer,reProduit,Stock_centre_primaire,Centre,Produit,Demande_massrouf,Employe_salarie,compteMagazinier,compteResponsable

admin.site.register(Produit)
admin.site.register(Magasinier)
admin.site.register(Fournisseur)
admin.site.register(Produit_Fournisseur)
admin.site.register(Achats_matiereP)
admin.site.register(Centre)
admin.site.register(Employe)
admin.site.register(Responsable)
admin.site.register(Absence_employe)
admin.site.register(Transfer)
admin.site.register(Achats_client)
admin.site.register(Rapport_responsable)
admin.site.register(Client)
admin.site.register(Achats_client_centre)
admin.site.register(paye_credit)
admin.site.register(reProduit)
admin.site.register(Stock_centre_primaire)
admin.site.register(Payement_sold_fournisseur)
admin.site.register(Demande_massrouf)
admin.site.register(Employe_salarie)
admin.site.register(compteResponsable)
admin.site.register(compteMagazinier)

