from django.urls import path,include
from . import views
urlpatterns = [

path('gestion_magasin/',views.afficher,name='magazinier'),
path('stock_magasin/',views.afficher_produits,name='stock_magasin'),
path('stock_magasin/supprimer_produit/<int:produit_id>/', views.supprimer_produit, name='supprimer_produit'),
path('modifier_produit/<int:produit_id>/', views.modifier_produit, name='modifier_produit'),
path('ajouter_produit/',views.ajouter_produit,name='ajouter_produit'),
path('magazin_statistiques/',views.afficherStatistiques,name='magazin_statistiques'),
path('centre_statistiques/',views.afficherCentreStatistiques,name='centre_statistiques'),
path('centre_statistiques/benifices_centre/',views.afficherbenifices_centre,name='benifices_centre'),
path('choisir_statistiques/',views.choisir_statistiques,name='choisir_statistiques'),
path('ventes_statistiques/',views.ventes_statistiques,name='ventes_statistiques'),

#path('stock_magasin/rechercher_produit/', views.rechercher_produit, name='rechercher_produit'),

path('gerer_achat/',views.afficher_fournisseur,name='gerer_fournisseur'),
path('gerer_achat/supprimer_fournisseur/<int:fournisseur_id>/', views.supprimer_fournisseur, name='supprimer_fournisseur'),
path('ajouter_fournisseur/',views.ajouter_fournisseur,name='ajouter_fournisseur'),
path('modifier_fournisseur/<int:fournisseur_id>/', views.modifier_fournisseur, name='modifier_fournisseur'),

path('choisir_option_achat/',views.choisir_option_achat,name='choisir_option_achat'),
path('listProduits_fournisseur/<int:fournisseur_id>/', views.afficher_listeP_fournisseur, name='listeProduit_fournisseur'),
path('listeProduits_fournisseur/supprimer_fournisseurP/<int:fournisseur_id>/<int:fournisseurP_id>/', views.supprimer_fournisseurP, name='supprimer_fournisseurP'),
path('modifier_fournisseurP/<int:fournisseur_id>/<int:fournisseurP_id>/', views.modifier_fournisseurP, name='modifier_fournisseurP'),
path('ajouter_produit_fournisseur/<int:fournisseur_id>/', views.ajouter_fournisseurP, name='ajouter_produitF'),

path('acheter_matiereP/<int:fournisseur_id>/<int:fournisseurP_id>/',views.acheter_matiereP,name='acheter_matiereP'),
path('voirAchat/<int:achat_id>',views.afficher_achat,name='voirAchat'),
path('listeAchatsMP/',views.afficher_listeAchat,name='listeAchatsMP'),
path('listeAchatsMP/supprimer_achat/<int:achat_id>',views.supprimer_achat,name='supprimer_achat'),

path('choisir_option_employe/',views.choisirE,name='choisir_option_employe'),
path('gerer_employe/',views.afficher_employés,name='liste_employé'),
path('ajouter_employe/',views.ajouter_employé,name='ajouter_employe'),
path('modifier_employe/<int:employe_id>/', views.modifier_employe, name='modifier_employe'),
path('gerer_employe/supprimer_employe/<int:employe_id>/',views.supprimer_employe,name='supprimer_employe'),

path('gerer_absenceE/',views.afficher_listeAbsence,name='gerer_absenceE'),
path('ajouter_absence/',views.ajouter_absenceE,name='ajouter_absence'),
path('gerer_absenceE/supprimer_absence/<int:absence_id>/',views.supprimer_absence,name='supprimer_absence'),
path('gerer_absenceE/supprimer_EmployeAbsent/<int:absence_id>/<int:employeA_id>',views.supprimer_EmployeAbsent,name='supprimer_EmployeAbsent'),
path('ajouter_employeAbsent/<int:absence_id>',views.ajouter_EmployeAbsent,name='ajouter_EmployeAbsent'),

path('ajouter_paiment_soldF/<int:fournisseur_id>/',views.ajouter_paiment_soldF,name='ajouter_paiment_soldF'),
path('liste_paimentSold/',views.afficher_listePaiment_soldF,name='listePaimentF'),
path('liste_paimentSold/supprimer_paimentSoldF/<int:paiment_id>',views.supprimer_paimentSoldF,name='supprimer_paimentSoldF'),

path('<int:selected_center>/gerer_employeRes/',views.gerer_employeRes,name='gerer_employeRes'),

path('<int:selected_center>/gerer_employeRes/liste_demandeMassrouf',views.afficher_liste_demMassrouf,name='liste_demandeMassrouf'),
path('<int:selected_center>/gerer_employeRes/ajouter_demande',views.ajouter_demMassrouf,name='ajouter_demande'),
path('<int:selected_center>/gerer_employeRes/modifier_demande/<int:demande_id>/',views.modifier_demMassrouf,name='modifier_demande'),
path('<int:selected_center>/gerer_employeRes/supprmier_demande/<int:demande_id>/',views.supprmier_demMassrouf,name='supprimer_demande'),

path('<int:selected_center>/gerer_employeRes/liste_PV',views.afficher_listePV,name='liste_PV'),
path('<int:selected_center>/gerer_employeRes/ajouter_rapport',views.ajouter_rapport,name='ajouter_rapport'),
path('<int:selected_center>/gerer_employeRes/supprimer_rapport/<int:rapport_id>/',views.supprimer_rapport,name='supprimer_rapport'),

path('gerer_employe/Liste_PVM',views.afficher_listePVM,name='liste_PVM'),
path('gerer_employe/gerer_salariePM',views.gerer_salariePM,name='gerer_salariePM'),

path('gerer_centres/',views.gerer_centres,name='gerer_centres'),
path('Transfer_produit/',views.Transfer_produit,name='Transfer_produit'),
path('annuler_transfer/<int:transfer_id>/',views.annuler_transfer,name='annuler_transfer'),
path('list_transfer/',views.list_transfer,name='list_transfer'),
path('list_client/',views.list_client,name='list_client'),
path('supprimer_client/<int:client_id>',views.supprimer_client,name='supprimer_client'),
path('modifier_client/<int:client_id>',views.modifier_client,name='modifier_client'),
path('choisir_centre/',views.choisir_centre,name='choisir_centre'),
path('<int:selected_center>/gestion_responsable/',views.gestion_responsable,name='gestion_responsable'),
path('<int:selected_center>/afficher_stock_centre/', views.afficher_stock_centre, name='afficher_stock_centre'),
path('<int:selected_center>/ajouter_reproduit/', views.ajouter_reproduit, name='ajouter_reproduit'),
path('<int:selected_center>/modifier_reProduit/<int:reproduit_id>/', views.modifier_reproduit, name='modifier_reProduit'),
path('<int:selected_center>/supprimer_reProduit/<int:reproduit_id>/', views.supprimer_reProduit, name='supprimer_reProduit'),
path('<int:selected_center>/ajouter_qte_reproduit/<int:reproduit_id>/', views.ajouter_qte_reproduit, name='ajouter_qte_reproduit'),
path('<int:selected_center>/choose_client_centre/',views.choose_client_centre,name='choose_client_centre'),
path('<int:selected_center>/ajouter_client_centre/',views.ajouter_client_centre,name='ajouter_client_centre'),
path('<int:selected_center>/select_product_type/<str:nom_client>',views.select_product_type,name='select_product_type'),
path('<int:selected_center>/vendre_produit_centre/<str:nom_client>/<str:category_vent>',views.vendre_produit_centre,name='vendre_produit_centre'),
path('<int:selected_center>/paye_achat_centre/<str:nom_client>/', views.paye_achat_centre, name='paye_achat_centre'),
path('gerer_client/',views.gerer_client,name='gerer_client'),
path('<int:selected_center>/gerer_client_centre/',views.gerer_client_centre,name='gerer_client_centre'),
path('choose_client/',views.choose_client,name='choose_client'),
path('ajouter_client/',views.ajouter_client,name='ajouter_client'),
path('vendre_produit/<str:nom_client>/', views.vendre_produit, name='vendre_produit'),
path('paye_achat/<str:nom_client>/', views.paye_achat, name='paye_achat'),
path('list_vente/', views.list_vente, name='list_vente'),
path('supprimer_vente/<int:achat_id>/', views.supprimer_vente, name='supprimer_vente'),
path('<int:selected_center>/supprimer_vente_centre/<int:achat_id>/', views.supprimer_vente_centre, name='supprimer_vente_centre'),
path('regle_credit/', views.regle_credit, name='regle_credit'),
path('modifier_credit/<int:credit_id>/', views.modifier_credit, name='modifier_credit'),
path('supprimer_credit/<int:credit_id>/', views.supprimer_credit, name='supprimer_credit'),
path('<int:selected_center>/regle_credit_centre/', views.regle_credit_centre, name='regle_credit_centre'),
path('<int:selected_center>/les_journale_centre/', views.les_journale_centre, name='les_journale_centre'),
path('<int:selected_center>/modifier_credit_centre/<int:credit_id>/', views.modifier_credit_centre, name='modifier_credit_centre'),
path('<int:selected_center>/supprimer_credit_centre/<int:credit_id>/', views.supprimer_credit_centre, name='supprimer_credit_centre'),
path('<int:selected_center>/journal_vente_centre/', views.journal_vente_centre, name='journal_vente_centre'),
path('<int:selected_center>/journal_transfer_centre/', views.journal_transfer_centre, name='journal_transfer_centre'),
path('list_vente_centre/', views.list_vente_centre, name='list_vente_centre'),
]
