# Generated by Django 5.0 on 2024-01-19 00:23

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Centre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numC', models.IntegerField(default=0)),
                ('designation', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomCl', models.CharField(max_length=50, unique=True)),
                ('prenomCl', models.CharField(max_length=50)),
                ('adrCl', models.CharField(max_length=50)),
                ('telephone', models.BigIntegerField()),
                ('credit', models.FloatField(default=0, max_length=10)),
                ('somme_paye', models.FloatField(default=0, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomF', models.CharField(max_length=50)),
                ('prenomF', models.CharField(max_length=50)),
                ('adrF', models.CharField(max_length=50)),
                ('telephone', models.BigIntegerField()),
                ('solde', models.FloatField(default=0, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Magasinier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomM', models.CharField(max_length=50)),
                ('prenomM', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomP', models.CharField(default='Produit', max_length=50)),
                ('designation', models.CharField(max_length=100, null=True)),
                ('qte', models.IntegerField(default=0)),
                ('prix_unitaire', models.FloatField(default=0, max_length=10)),
                ('prix_total', models.FloatField(default=0, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Produit_Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomP', models.CharField(default='Produit', max_length=50)),
                ('designation', models.CharField(default='des', max_length=100)),
                ('qte', models.IntegerField(default=0)),
                ('prix_unitaire', models.FloatField(default=0, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomE', models.CharField(max_length=50)),
                ('prenomE', models.CharField(max_length=50)),
                ('adrE', models.CharField(max_length=50)),
                ('telephone', models.BigIntegerField()),
                ('Salarie_jour', models.FloatField(default=0)),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magasinier.centre')),
            ],
        ),
        migrations.CreateModel(
            name='Demande_massrouf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_dem', models.DateField(default=datetime.datetime.now)),
                ('massrouf', models.FloatField(default=0, max_length=10)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magasinier.employe')),
            ],
        ),
        migrations.CreateModel(
            name='Absence_employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_absence', models.DateField(default=datetime.datetime.now, unique=True)),
                ('Employe_absente', models.ManyToManyField(related_name='date_absence', to='magasinier.employe')),
            ],
        ),
        migrations.CreateModel(
            name='Employe_salarie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('année', models.BigIntegerField(default=1)),
                ('mois', models.CharField(max_length=10)),
                ('massrouf_total', models.FloatField(default=0, max_length=10)),
                ('absences_count', models.IntegerField(default=0)),
                ('Salarie', models.FloatField(default=0, max_length=10)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magasinier.employe')),
            ],
        ),
        migrations.CreateModel(
            name='paye_credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modification', models.DateField(default=datetime.datetime.now)),
                ('nom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magasinier.client')),
            ],
        ),
        migrations.CreateModel(
            name='Payement_sold_fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_payement', models.DateField(default=datetime.datetime.now)),
                ('montant_payé', models.FloatField(default=0, max_length=10)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magasinier.fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='Achats_client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_achat', models.DateField(default=datetime.datetime.now)),
                ('qte', models.IntegerField(default=1)),
                ('prix_unitaire', models.FloatField(default=0, max_length=10)),
                ('somme_paye', models.FloatField(default=0, max_length=10)),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magasinier.client')),
                ('Produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magasinier.produit')),
            ],
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='produits_fournisseur',
            field=models.ManyToManyField(related_name='Fournisseurs', to='magasinier.produit_fournisseur'),
        ),
        migrations.CreateModel(
            name='Achats_matiereP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_achat', models.DateTimeField(default=datetime.datetime.now)),
                ('qte', models.IntegerField(default=1)),
                ('Montant_achat', models.FloatField(default=0, max_length=10)),
                ('Montant_payé', models.FloatField(default=0, max_length=10)),
                ('sold_achat', models.FloatField(default=0, max_length=10)),
                ('Fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magasinier.fournisseur')),
                ('Produit', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='magasinier.produit')),
                ('Produit_Fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magasinier.produit_fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomR', models.CharField(max_length=50)),
                ('prenomR', models.CharField(max_length=50)),
                ('adrR', models.CharField(max_length=50)),
                ('telephone', models.BigIntegerField()),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magasinier.centre')),
            ],
        ),
        migrations.CreateModel(
            name='Rapport_responsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_R', models.DateField(default=datetime.datetime.now)),
                ('Rapport', models.FileField(default=None, upload_to='pdfs/')),
                ('centre', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='magasinier.centre')),
                ('demandes_massrouf', models.ManyToManyField(related_name='rapports', to='magasinier.demande_massrouf')),
                ('responsable', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='magasinier.responsable')),
            ],
        ),
        migrations.AddField(
            model_name='demande_massrouf',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magasinier.responsable'),
        ),
        migrations.CreateModel(
            name='Stock_centre_primaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomP', models.CharField(default='Produit', max_length=50)),
                ('designation', models.CharField(max_length=100, null=True)),
                ('qte', models.IntegerField(default=1)),
                ('prix_unitaire', models.FloatField(default=0, max_length=10)),
                ('Centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magasinier.centre')),
            ],
        ),
        migrations.CreateModel(
            name='reProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomP', models.CharField(default='Produit', max_length=50)),
                ('qte_Produit_primaire', models.IntegerField(default=1)),
                ('designation', models.CharField(max_length=100, null=True)),
                ('qte_reProduit', models.IntegerField(default=1)),
                ('prix_unitaire', models.FloatField(default=0, max_length=10)),
                ('Centre', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='magasinier.centre')),
                ('Produit_primaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magasinier.stock_centre_primaire')),
            ],
        ),
        migrations.CreateModel(
            name='Achats_client_centre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_achat', models.DateField(default=datetime.datetime.now)),
                ('qte', models.IntegerField(default=1)),
                ('prix_unitaire', models.FloatField(default=0, max_length=10)),
                ('somme_paye', models.FloatField(default=0, max_length=10)),
                ('Centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magasinier.centre')),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magasinier.client')),
                ('reproduit', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='magasinier.reproduit')),
                ('produit_primaire', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='magasinier.stock_centre_primaire')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_transfer', models.DateField(default=datetime.datetime.now)),
                ('Qte', models.IntegerField()),
                ('Centre_transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magasinier.centre')),
                ('produit_transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magasinier.produit')),
            ],
        ),
    ]
