# Generated by Django 5.0 on 2024-01-02 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasinier', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='Salarie_mois',
        ),
        migrations.CreateModel(
            name='Employe_salarie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('année', models.BigIntegerField(default=1)),
                ('mois', models.CharField(max_length=10)),
                ('massrouf_total', models.FloatField(default=0, max_length=10)),
                ('absences_count', models.IntegerField(default=0, max_length=10)),
                ('Salarie', models.FloatField(default=0, max_length=10)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magasinier.employe')),
            ],
        ),
    ]
