# Generated by Django 5.0 on 2023-12-24 22:27

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasinier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absence_employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_absence', models.DateField(default=datetime.datetime.now, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Achats_centre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_achat', models.DateField(default=datetime.datetime.now)),
                ('qte', models.IntegerField(default=1)),
                ('Montant_achat', models.FloatField(default=0, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Achats_client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_achat', models.DateField(default=datetime.datetime.now)),
                ('qte', models.IntegerField(default=1)),
                ('Montant_achat', models.FloatField(default=0, max_length=10)),
                ('solde', models.FloatField(default=0, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Achats_matiereP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_achat', models.DateField(default=datetime.datetime.now)),
                ('qte', models.IntegerField(default=1)),
                ('Montant_achat', models.FloatField(default=0, max_length=10)),
                ('sold_achat', models.FloatField(default=0, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Magasinier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomM', models.CharField(max_length=50)),
                ('prenomM', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomP', models.CharField(default='Produit', max_length=50)),
                ('designation', models.CharField(max_length=100, null=True)),
                ('qte', models.IntegerField(default=1)),
                ('prix_unitaire', models.FloatField(default=0, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Produit_Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomP', models.CharField(default='Produit', max_length=50)),
                ('designation', models.CharField(max_length=100, null=True)),
                ('qte', models.IntegerField(default=1)),
                ('prix_unitaire', models.FloatField(default=0, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Rapport_responsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_R', models.DateField(default=datetime.datetime.now, unique=True)),
                ('Rapport', models.FileField(default=FileNotFoundError, upload_to='pdfs/')),
            ],
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomR', models.CharField(max_length=50)),
                ('prenomR', models.CharField(max_length=50)),
                ('adrR', models.CharField(max_length=50)),
                ('telephone', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stock_centre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomP', models.CharField(default='Produit', max_length=50)),
                ('designation', models.CharField(max_length=100, null=True)),
                ('qte', models.IntegerField(default=1)),
                ('prix_unitaire', models.FloatField(default=0, max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Produits',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='adresse',
            new_name='adrCl',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='nom',
            new_name='nomCl',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='prenom',
            new_name='prenomCl',
        ),
        migrations.RenameField(
            model_name='employe',
            old_name='adresse',
            new_name='adrE',
        ),
        migrations.RenameField(
            model_name='employe',
            old_name='nom',
            new_name='nomE',
        ),
        migrations.RenameField(
            model_name='employe',
            old_name='prenom',
            new_name='prenomE',
        ),
        migrations.RenameField(
            model_name='fournisseur',
            old_name='adresse',
            new_name='adrF',
        ),
        migrations.RenameField(
            model_name='fournisseur',
            old_name='nom',
            new_name='nomF',
        ),
        migrations.RenameField(
            model_name='fournisseur',
            old_name='prenom',
            new_name='prenomF',
        ),
        migrations.RemoveField(
            model_name='centre',
            name='code',
        ),
        migrations.RemoveField(
            model_name='centre',
            name='désignation',
        ),
        migrations.RemoveField(
            model_name='client',
            name='code',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='code',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='salaire_jour',
        ),
        migrations.RemoveField(
            model_name='fournisseur',
            name='code',
        ),
        migrations.AddField(
            model_name='centre',
            name='designation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='centre',
            name='numC',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employe',
            name='Salarie_jour',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='client',
            name='credit',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='employe',
            name='telephone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='solde',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='telephone',
            field=models.BigIntegerField(),
        ),
        migrations.AddField(
            model_name='absence_employe',
            name='Employe_absente',
            field=models.ManyToManyField(related_name='date_absence', to='magasinier.employe'),
        ),
        migrations.AddField(
            model_name='achats_centre',
            name='Centre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magasinier.centre'),
        ),
        migrations.AddField(
            model_name='achats_client',
            name='Centre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magasinier.centre'),
        ),
        migrations.AddField(
            model_name='achats_client',
            name='Client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magasinier.client'),
        ),
        migrations.AddField(
            model_name='achats_matierep',
            name='Fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magasinier.fournisseur'),
        ),
        migrations.AddField(
            model_name='achats_matierep',
            name='Magasinier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magasinier.magasinier'),
        ),
        migrations.AddField(
            model_name='achats_client',
            name='Magasinier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magasinier.magasinier'),
        ),
        migrations.AddField(
            model_name='achats_centre',
            name='Magasinier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magasinier.magasinier'),
        ),
        migrations.AddField(
            model_name='achats_client',
            name='Produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magasinier.produit'),
        ),
        migrations.AddField(
            model_name='achats_centre',
            name='Produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magasinier.produit'),
        ),
        migrations.AddField(
            model_name='achats_matierep',
            name='Produit_Fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magasinier.produit_fournisseur'),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='produits_fournisseur',
            field=models.ManyToManyField(related_name='Fournisseurs', to='magasinier.produit_fournisseur'),
        ),
        migrations.AddField(
            model_name='responsable',
            name='centre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magasinier.centre'),
        ),
        migrations.AddField(
            model_name='rapport_responsable',
            name='Responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magasinier.responsable'),
        ),
        migrations.AddField(
            model_name='stock_centre',
            name='Centre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magasinier.centre'),
        ),
    ]
