# Generated by Django 5.0 on 2024-01-02 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasinier', '0002_remove_employe_salarie_mois_employe_salarie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe_salarie',
            name='absences_count',
            field=models.IntegerField(default=0),
        ),
    ]
