# Generated by Django 5.0 on 2024-01-19 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasinier', '0002_compte'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='compte',
            new_name='compteMagazinier',
        ),
        migrations.CreateModel(
            name='compteResponsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='username', max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magasinier.responsable')),
            ],
        ),
    ]
