# Generated by Django 5.0 on 2023-12-24 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasinier', '0002_absence_employe_achats_centre_achats_client_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qte', models.IntegerField()),
                ('Centre_transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magasinier.centre')),
                ('produit_transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magasinier.produit')),
            ],
        ),
    ]
