# Generated by Django 5.0 on 2024-01-02 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasinier', '0003_alter_employe_salarie_absences_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapport_responsable',
            name='centre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='magasinier.centre'),
        ),
    ]
