# Generated by Django 5.0 on 2023-12-24 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasinier', '0003_transfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='Centre_transfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magasinier.stock_centre'),
        ),
    ]
