# Generated by Django 5.0 on 2024-01-19 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasinier', '0003_rename_compte_comptemagazinier_compteresponsable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comptemagazinier',
            old_name='password',
            new_name='password1',
        ),
        migrations.RenameField(
            model_name='compteresponsable',
            old_name='password',
            new_name='password1',
        ),
        migrations.AddField(
            model_name='comptemagazinier',
            name='password2',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='compteresponsable',
            name='password2',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
