# Generated by Django 5.0 on 2023-12-25 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasinier', '0004_alter_transfer_centre_transfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centre',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
