# Generated by Django 5.0 on 2024-01-02 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasinier', '0004_rapport_responsable_centre'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='prix_total',
            field=models.FloatField(default=0, max_length=10),
        ),
    ]
