# Generated by Django 5.0 on 2024-01-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasinier', '0005_produit_prix_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='qte',
            field=models.IntegerField(default=0),
        ),
    ]
