# Generated by Django 5.0 on 2023-12-25 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasinier', '0005_alter_centre_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='Centre_transfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magasinier.centre'),
        ),
    ]
