# Generated by Django 5.0 on 2024-01-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasinier', '0005_rename_password2_comptemagazinier_confirm_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comptemagazinier',
            name='username',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='compteresponsable',
            name='username',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
