# Generated by Django 5.0 on 2024-01-12 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasinier', '0006_alter_produit_qte'),
    ]

    operations = [
        migrations.AddField(
            model_name='achats_matierep',
            name='Produit',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='magasinier.produit'),
        ),
    ]
