# Generated by Django 5.0 on 2023-12-25 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasinier', '0006_alter_transfer_centre_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='designation',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
