# Generated by Django 5.0 on 2024-01-12 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasinier', '0007_achats_matierep_produit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit_fournisseur',
            name='qte',
            field=models.IntegerField(default=0),
        ),
    ]
