# Generated by Django 5.0 on 2023-12-25 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasinier', '0008_reproduit'),
    ]

    operations = [
        migrations.AddField(
            model_name='reproduit',
            name='Centre',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='magasinier.centre'),
        ),
    ]
