# Generated by Django 5.0 on 2023-12-25 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magasinier', '0009_reproduit_centre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reproduit',
            old_name='Stock',
            new_name='Produit_primaire',
        ),
    ]
