# Generated by Django 5.0 on 2023-12-25 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasinier', '0010_rename_stock_reproduit_produit_primaire'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reproduit',
            old_name='qte',
            new_name='qte_Produit_primaire',
        ),
        migrations.AddField(
            model_name='reproduit',
            name='qte_reProduit',
            field=models.IntegerField(default=1),
        ),
    ]
