# Generated by Django 5.0 on 2023-12-26 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magasinier', '0012_remove_achats_client_montant_achat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achats_client',
            name='Magasinier',
        ),
    ]
