# Generated by Django 5.0 on 2023-12-26 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasinier', '0014_alter_achats_client_centre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='nomCl',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
