# Generated by Django 5.0 on 2023-12-26 15:34

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasinier', '0016_remove_achats_client_centre'),
    ]

    operations = [
        migrations.CreateModel(
            name='paye_credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('payement', models.FloatField(default=0, max_length=10)),
                ('nom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magasinier.client')),
            ],
        ),
    ]
