# Generated by Django 5.0 on 2023-12-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasinier', '0017_paye_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='somme_paye',
            field=models.FloatField(default=0, max_length=10),
        ),
    ]
