# Generated by Django 5.0 on 2023-12-26 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magasinier', '0018_client_somme_paye'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paye_credit',
            name='payement',
        ),
    ]
