# Generated by Django 5.0 on 2023-12-26 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasinier', '0020_remove_client_somme_paye_paye_credit_somme_paye'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='somme_paye',
            field=models.FloatField(default=0, max_length=10),
        ),
    ]
