# Generated by Django 5.0 on 2023-12-26 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magasinier', '0021_client_somme_paye'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paye_credit',
            name='somme_paye',
        ),
    ]
