# Generated by Django 5.0 on 2023-12-27 18:23

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasinier', '0024_transfer_date_transfer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='designation',
        ),
        migrations.AddField(
            model_name='client',
            name='Centre',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='magasinier.centre'),
        ),
        migrations.CreateModel(
            name='Achats_client_centre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_achat', models.DateField(default=datetime.datetime.now)),
                ('qte', models.IntegerField(default=1)),
                ('Cente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magasinier.centre')),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magasinier.client')),
                ('reProduit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magasinier.reproduit')),
            ],
        ),
    ]
