# Generated by Django 5.0 on 2023-12-27 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magasinier', '0025_remove_transfer_designation_client_centre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='Centre',
        ),
    ]
