# Generated by Django 5.0 on 2023-12-27 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magasinier', '0028_remove_client_centre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achats_client_centre',
            name='Cente',
        ),
        migrations.RemoveField(
            model_name='achats_client_centre',
            name='Client',
        ),
    ]
