# Generated by Django 5.0 on 2023-12-27 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magasinier', '0029_remove_achats_client_centre_cente_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Achats_client_centre',
        ),
    ]
