# Generated by Django 5.0 on 2023-12-27 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magasinier', '0031_achats_client_centre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achats_client_centre',
            old_name='Cente',
            new_name='Centre',
        ),
    ]
