# Generated by Django 5.0 on 2023-12-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasinier', '0032_rename_cente_achats_client_centre_centre'),
    ]

    operations = [
        migrations.AddField(
            model_name='achats_client',
            name='prix_unitaire',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='achats_client_centre',
            name='prix_unitaire',
            field=models.FloatField(default=0, max_length=10),
        ),
    ]
