# Generated by Django 5.0 on 2023-12-28 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasinier', '0033_achats_client_prix_unitaire_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achats_client_centre',
            name='reProduit',
        ),
        migrations.CreateModel(
            name='Stock_centre_total',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produit_primaire', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='magasinier.stock_centre')),
                ('produit_reproduit', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='magasinier.reproduit')),
            ],
        ),
        migrations.AddField(
            model_name='achats_client_centre',
            name='produit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='magasinier.stock_centre_total'),
            preserve_default=False,
        ),
    ]
