# Generated by Django 5.0 on 2023-12-28 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasinier', '0034_remove_achats_client_centre_reproduit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achats_client_centre',
            name='produit',
        ),
        migrations.AddField(
            model_name='achats_client_centre',
            name='produit_primaire',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='magasinier.stock_centre'),
        ),
        migrations.AddField(
            model_name='achats_client_centre',
            name='reproduit',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='magasinier.reproduit'),
        ),
        migrations.DeleteModel(
            name='Stock_centre_total',
        ),
    ]
