# Generated by Django 5.0 on 2023-12-29 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magasinier', '0035_remove_achats_client_centre_produit_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stock_centre',
            new_name='Stock_centre_primaire',
        ),
    ]
