# Generated by Django 5.0 on 2023-12-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasinier', '0036_rename_stock_centre_stock_centre_primaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='achats_client_centre',
            name='somme_paye',
            field=models.FloatField(default=0, max_length=10),
        ),
    ]
