# Generated by Django 5.0 on 2023-12-29 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasinier', '0037_achats_client_centre_somme_paye'),
    ]

    operations = [
        migrations.AddField(
            model_name='achats_client',
            name='somme_paye',
            field=models.FloatField(default=0, max_length=10),
        ),
    ]
