# Generated by Django 5.0 on 2023-12-30 00:35

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasinier', '0038_achats_client_somme_paye'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achats_matierep',
            name='Magasinier',
        ),
        migrations.AddField(
            model_name='achats_matierep',
            name='Montant_payé',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='produit_fournisseur',
            name='designation',
            field=models.CharField(default='des', max_length=100),
        ),
        migrations.CreateModel(
            name='Payement_sold_fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_payement', models.DateField(default=datetime.datetime.now)),
                ('montant_payé', models.FloatField(default=0, max_length=10)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magasinier.fournisseur')),
            ],
        ),
    ]
